# Mewwme config file via .yaml
# Version 6.0.5
# You can use ${} to pass an enviroment varible from .env file
# Eg:
# something: ${DATA}

bot:
  TOKEN: ${BOT_TOKEN}
  EMBED_COLOR: "#f4e0c7"
  OWNER_IDS: ["742457036914294855", "176144329046360064"]
  LANGUAGE: "en" # You can set it to en or you can customize it with your language
  LIMIT_TRACK: 100 # The number of tracks you want to limit
  LIMIT_PLAYLIST: 50 # The number of playlist you want to limit
  SAFE_ICONS_MODE: false # If the new icon doesn't appears, try change this to true
  SAFE_PLAYER_MODE: true # Set to embed instead of image for avoid error
  DELETE_MSG_TIMEOUT: 5000 # Set to 0 if you don't want to delete message
  DEBUG_MODE: false
  GENIUS_APIKEY: "oo9GZ7UBa5Z4wb_zu8i2-K-RpxUHK1iURy61q8ETRiYTs1z6HMc3S9NN38Js68hX"

  # set music card settings
  # mewwme, themes1, themes2, themes3, themes4, themes5, themes6, themes7, themes8
  # themes9, themes10, themes11, themes12, themes13, themes14, themes15, themes16, themes17"
  THEMES_MUSIC: "mewwme"

  # set presence activity settings for bot
  BOT_ACTIVITY1: ""
  BOT_ACTIVITY2: ""
  BOT_ACTIVITY3: ""
  BOT_ACTIVITY_TYPE: 1 # 0 = PLAYING, 1 = STREAMING, 2 = LISTENING, 3 = WATCHING, 4 = CUSTOM. 5 = COMPETING
  STREAM_URL: "https://www.youtube.com/watch?v=F-wbcMyeq4A" # set stream url activity, support youtube, twitch only
  BOT_STATUS: "idle" # online, idle, dnd, invisible
  CUSTOM_STATUS: "MADE BY TRAGIC" # set custom status if type is 4

  IMGURL_GUILDADD: "https://cdn.is-a.fun/bot/mewwme/thankyou.png"
  IMGURL_HELPMENU: "https://cdn.is-a.fun/bot/mewwme/help.png"
  IMGURL_COMMANDMENU: "https://cdn.is-a.fun/bot/mewwme/cmd.png"
  REQUEST_IMAGE: "https://cdn.is-a.fun/bot/mewwme/req.png"
  IMGURL_MENTION: "https://cdn.is-a.fun/bot/mewwme/help.png"
  # button link
  BUYCODE_URL: "https://builtbybit.com/resources/music-discord-bot-with-premium-system.35681/"
  PARTNER_NAME: "Partner"
  PARTNER_URL: "https://discord.gg/SbqxZzUS3F"
  SERVER_SUPPORT: "https://discord.gg/mewwme"
  VOTEURL: "https://top.gg/bot/928711702596423740"
  DEVELOPER: "L RMN"
  DEVELOPER_URL: "https://is-a.fun"
  PATREON_URL: "https://www.patreon.com/mewwme"
  WEBSITE_URL: "https://meww.me"
  DONATE_URL: "https://meww.me/sponsor"
  INVITE_URL: "https://discord.com/api/oauth2/authorize?client_id=928711702596423740&permissions=551940385840&response_type=code&redirect_uri=https%3A%2F%2Fdiscord.gg%2Fmewwme&scope=guilds.join+bot+applications.commands"
  TERMS_URL: "https://meww.me/termsofservice"
  PRIVACY_URL: "https://meww.me/privacy"
  DOCS_URL: "https://docs.meww.me"

lavalink:
  SEARCH_ENGINE: "youtube_music" # default ( youtube, youtube_music, soundcloud )
    # Your spotify id and secret, you can get it from here: https://developer.spotify.com/
    # If you don't have or don't want, you can disable it
  SPOTIFY:
    enable: true
    id: fdf0e2d1da9e40169b5918f73addae04
    secret: db0fa34ff766490e87e9996c0ae844e0

  DEFAULT: ["yoasobi", "one oke rock", "blackpink"]

  NP_REALTIME: false # Enable this if you want to use realtime duation in nowplaying command

  LEAVE_TIMEOUT: 300000 # The number of leave time you want

  # You can add more lavalink server!
  NODES:
    [
      {
        url: "34.142.204.199:2333",
        name: "mewwme",
        auth: "madebytragic",
        secure: false,
      },
    ]
  SHOUKAKU_OPTIONS:
    {
      moveOnDisconnect: true,
      resumable: true,
      resumableTimeout: 600,
      reconnectTries: "Infinity",
      restTimeout: 3000,
    }


features:
    # Note: If you enter an invalid driver, bot will use json driver as default
    # Config depend on driver, you can see sample config at src/database/driver
    # mongodb, mysql, json, postgres
 # DATABASE:
 #   driver: "mysql" # Note: mongodb, mysql, json, postgres
 #   config:
 #     host: "panel.mangex.pro"
 #     user: "u136_lwAyXFfhha"
 #     password: "o6g+s+1gq4PBJ^Uf2A5XLOhI"
 #     database: "s136_mewwme"
  DATABASE:
    driver: "mongodb" # mongodb, mysql, json, postgres
    config: { uri: "mongodb+srv://mewwme:mewwme@mewwme.icahpka.mongodb.net/mewwme?retryWrites=true&w=majority" }

  MESSAGE_CONTENT:
    enable: true
    commands:
      enable: true
      prefix: "me" # The prefix you want

  AUTOFIX_LAVALINK: # Fix the lavalink server when the current is down
    enable: true
    reconnectTries: 1
    restTimeout: 3000

  WEB_SERVER:
    enable: true # Must enable this before using ws
    PORT: 3022
    TOPGG_WEBHOOK_PORT: 3025
    TOPGG_WEBHOOK_AUTH: "madebytragic"
    TOPGG_GUILD_ID: "1088032923443277824"
    TOPGG_VOTE_LOG_CHANNEL_ID: "1144258683614806027"
    TOPGG_VOTE_IMG: "https://cdn.is-a.fun/bot/mewwme/vote.png"
  # statistics for bot with top.gg
    TOPGG_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkyODcxMTcwMjU5NjQyMzc0MCIsImJvdCI6dHJ1ZSwiaWF0IjoxNzA2MzU0NDM4fQ.IP48n2-4eL3fWYemwGAWHAyA8JMH905v4T1OtmHR5VY"
  
    websocket:
      enable: true
      host: "0.0.0.0" # Default is 0.0.0.0
      secret: "-19023454588-MEWWME" # You must add your secret key to use ws. A secret key is anything you want
      auth: true
      trusted: ["http://34.142.204.199:3022"]

  # Your id or friend id (disable global command)
  DEV_ID: []

# Emoji config for discord message content in select menu
# https://discord.gg/mewwme join the discord server if you want to use existing emoji
Emoji:
  E_HOME: "<:home:1193100237133336670>"
  E_ADMIN: "<:admin:1193100129020944454>"
  E_DEV: "<:devme:1203372399135957012>"
  E_SETTING: "<:setting:1193100341261119598>"
  E_FILTER: "<:switch:1196007160279203841>"
  E_PLAYLIST: "<:playlist:1193105976694407208>"
  E_UTILS: "<:utils:1203371744900153436>"
  E_ALLCMD: "<:meall:1193100157928099931>"
  E_MUSIC: "<:disc:1196006944746524764>"
  E_INFO: "<:info:1193100286881964104>"
  E_INVITE: "<:invite:1193101531189354597>"
  E_SUPPORT: "<:supportme:1193101738195034162>"
  E_VOTE: "<:topggvote:1193101695761260564>"
  E_WEBSITE: "<:meweb:1193107047793840220>"
  E_LOADING: "<a:loading:1169254882193186847>"
  E_PRIVACY: "<:legal:1193105018887344169>"
  E_TERMS: "<:legal:1193105018887344169>"
  E_DOCS: "<:meweb:1193107047793840220>"
  E_PREMIUM: "<:prem:1193109484688642118>"
  E_PARTNER: "<:partner:1193128320380964934>"
  E_DONATE: "<:sponsor:1193323172230090762>"
  
  E_FILTER_FREE: "<:singing:1196006929932234782>"
  E_FILTER_PREMIUM: "<:prem:1193109484688642118>"
  E_FILTER_RESET: "<:loop:1193113331767185499>"

ServerSupport:
# set welcomer event
  WELCOME_CHANNEL_ID: "1091287764252753981"
  LEAVE_CHANNEL_ID: "1091212076246110248"
  GUILDID_WELCOMER: "1088032923443277824"

# set channel support for bot event
  UPDATE_CHANNEL_ID: "1184233810930454638"
  SUGGESTION_CHANNEL_ID: "1189014444680958052"
  BUG_REPORT_CHANNEL_ID: "1189014283053432924"

# set webhook url settings for bot guild add/guild remove logs
  BOTLOGS_JOINLEFT: "https://discord.com/api/webhooks/1180798962945511485/FT5-T7nxBodAvOlFVWVv-mvMd8SQi8K-lD5sgSM1Ua-qcIFzk1HsAF391KbQVZUa9JlN"

# set webhook url settings for redeem logs
  REDEEM_LOGS: "https://discord.com/api/webhooks/1185670160586133647/40sH8Hn-KCz5iGVQ-W-Uinm1auhvwkw6SJSJZ3XHYvv3iZnaYHnYIeVbAY6Y-PttrPKD" # set webhook url for redeem logs 


# APIKEY FROM https://api-ninjas.com/
  QUOTES_API_KEY: "lYunAQzpvqzsPG2FPWpBI385tU2chaXEgFI6wtrE"