# Mewwme Version 7.0.0

bot:
  TOKEN: "your token bot"
  EMBED_COLOR: "#f4e0c7" # Global color for embeds
  OWNER_IDS: ["742457036914294855", "176144329046360064"]
  LANGUAGE: "en" # You can set it to en or you can customize it with your language
  LIMIT_TRACK: 100 # The number of tracks you want to limit
  LIMIT_PLAYLIST: 50 # The number of playlist you want to limit
  DELETE_MSG_TIMEOUT: 5000 # Set to 0 if you don't want to delete message
  DEBUG_MODE: false
  # genius api key from https://genius.com/developers  (lyrics commands)
  GENIUS_APIKEY: "your genius api key"
  # statistics for bot with top.gg
  TOPGG_TOKEN: "your token top gg"

  # set music card settings
  # mewwme, themes1, themes2, themes3, themes4, themes5, themes6, themes7, themes8
  # themes9, themes10, themes11, themes12, themes13, themes14, themes15, themes16, themes17, themes18"
  THEMES_MUSIC: "mewwme"

  # set presence activity settings for bot
  BOT_ACTIVITY1: ""
  BOT_ACTIVITY2: ""
  BOT_ACTIVITY3: ""
  BOT_ACTIVITY_TYPE: 1 # 0 = PLAYING, 1 = STREAMING, 2 = LISTENING, 3 = WATCHING, 4 = CUSTOM. 5 = COMPETING
  STREAM_URL: "https://www.youtube.com/watch?v=F-wbcMyeq4A" # set stream url activity, support youtube, twitch only
  BOT_STATUS: "idle" # online, idle, dnd, invisible
  CUSTOM_STATUS: "MADE BY TRAGIC" # set custom status if type is 4

  IMGURL_GUILDADD: "https://cdn.is-a.fun/bot/mewwme/meadd.png"
  IMGURL_MENUHELP: "https://cdn.is-a.fun/bot/mewwme/mehelp.png"
  IMGURL_COMMANDMENU: "https://cdn.is-a.fun/mewwme/mecmd.png"
  REQUEST_IMAGE: "https://cdn.is-a.fun/bot/mewwme/mereq.png"
  IMGURL_MENTION: "https://cdn.is-a.fun/bot/mewwme/mewelcy.png"

  # button link
  DEVELOPER_NAME: "L RMN"
  DEVELOPER_URL: "https://is-a.fun"
  DONATE_URL: "https://www.patreon.com/mewwme"
  SERVER_SUPPORT: "https://discord.gg/mewwme"
  VOTE_URL: "https://top.gg/bot/928711702596423740"
  INVITE_URL: "https://discord.com/api/oauth2/authorize?client_id=928711702596423740&permissions=551940385840&response_type=code&redirect_uri=https%3A%2F%2Fdiscord.gg%2Fmewwme&scope=guilds.join+bot+applications.commands"

lavalink:
  SEARCH_ENGINE: "youtube_music" # default ( youtube, youtube_music, soundcloud )
    # Your spotify id and secret, you can get it from here: https://developer.spotify.com/
    # If you don't have or don't want, you can disable it
  SPOTIFY:
    enable: true
    id: "your client id"
    secret: "your secret"

  DEFAULT: ["feby putri", "fiersa besari", "biru baru"] # suggestions song /commands

  NP_REALTIME: false #beta (Enable this if you want to use realtime duation in nowplaying command)

  LEAVE_TIMEOUT: 300000 # The number of leave time you want

  # You can add more lavalink server!
  NODES:
    [
      # node region Asia/Jakarta
      {
        url: "34.142.204.199:2333",
        name: "mewwme",
        auth: "madebytragic",
        secure: false,
      },
    ]
  SHOUKAKU_OPTIONS:
    {
      moveOnDisconnect: true,
      resumable: true,
      resumableTimeout: 600,
      reconnectTries: "Infinity",
      restTimeout: 3000,
    }


features:
    # Note: If you enter an invalid driver, bot will use json driver as default
    # Config depend on driver, you can see sample config at src/database/driver or README.md
    # mongodb, mysql, json, postgres
  DATABASE:
    driver: "json" # mongodb, mysql, json, postgres
    config: { path: "./mewwme.database.json" }

  MESSAGE_CONTENT:
    enable: true
    commands:
      enable: true
      prefix: ">" # The prefix you want

  AUTOFIX_LAVALINK: # Fix the lavalink server when the current is down
    enable: true
    reconnectTries: 3
    restTimeout: 3000

  WEB_SERVER:
    enable: false # Must enable this before using ws
    PORT: 6969
    websocket:
      enable: false
      host: "0.0.0.0" # Default is 0.0.0.0
      secret: "-19023454588-MEWWME" # You must add your secret key to use ws. A secret key is anything you want
      auth: false
      trusted: ["http://localhost:6969"]

  # Your id or friend id (disable global command)
  DEV_ID: []

# Emoji config for discord message content in select menu
# https://discord.gg/mewwme join the discord server if you want to use existing emoji
Emoji:
  E_HOME: "<:home:1193100237133336670>"
  E_ADMIN: "<:admin:1193100129020944454>"
  E_DEV: "<:devme:1203372399135957012>"
  E_SETTING: "<:setting:1193100341261119598>"
  E_FILTER: "<:switch:1196007160279203841>"
  E_PLAYLIST: "<:playlist:1193105976694407208>"
  E_UTILS: "<:utils:1203371744900153436>"
  E_ALLCMD: "<:meall:1193100157928099931>"
  E_MUSIC: "<:disc:1196006944746524764>"
  E_INFO: "<:info:1193100286881964104>"
  E_LOADING: "<a:loading:1169254882193186847>"

# Emoji button
  E_DONATE: "<:sponsor:1193323172230090762>"
  E_INVITE: "<:invite:1193101531189354597>"
  E_SUPPORT: "<:supportme:1193101738195034162>"
  E_VOTE: "<:topggvote:1193101695761260564>"

ServerSupport:
# set channel support for bot event
  UPDATE_CHANNEL_ID: "your channel id"
  SUGGESTION_CHANNEL_ID: "your channel id"
  BUG_REPORT_CHANNEL_ID: "your channel id"
# set webhook url settings for bot guild add/guild remove logs
  BOTLOGS_JOINLEFT: "your webhook url"

