# Mewwme config file via .yaml
# Version 6.0.5
# You can use ${} to pass an enviroment varible from .env file
# Eg:
# something: ${DATA}

bot:
  TOKEN: ${BOT_TOKEN}
  EMBED_COLOR: "#f4e0c7"
  OWNER_IDS: ["742457036914294855", "176144329046360064"]
  LANGUAGE: "en" # You can set it to en or you can customize it with your language
  LIMIT_TRACK: 100 # The number of tracks you want to limit
  LIMIT_PLAYLIST: 50 # The number of playlist you want to limit
  DELETE_MSG_TIMEOUT: 5000 # Set to 0 if you don't want to delete message
  DEBUG_MODE: false
  # genius api key from https://genius.com/developers
  GENIUS_APIKEY: "oo9GZ7UBa5Z4wb_zu8i2-K-RpxUHK1iURy61q8ETRiYTs1z6HMc3S9NN38Js68hX"
  # statistics for bot with top.gg
  TOPGG_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwOTAxMjAxMzYxNjc1Mzg3NDgiLCJib3QiOnRydWUsImlhdCI6MTY5NzM4MzEzNX0.PI3t4wSbBGQ6nf3tOjwWD8Tx2stAU3u83_I48tILpu0"

  # set music card settings
  # mewwme, themes1, themes2, themes3, themes4, themes5, themes6, themes7, themes8
  # themes9, themes10, themes11, themes12, themes13, themes14, themes15, themes16, themes17, themes18"
  THEMES_MUSIC: "mewwme"

  # set presence activity settings for bot
  BOT_ACTIVITY1: ""
  BOT_ACTIVITY2: ""
  BOT_ACTIVITY3: ""
  BOT_ACTIVITY_TYPE: 1 # 0 = PLAYING, 1 = STREAMING, 2 = LISTENING, 3 = WATCHING, 4 = CUSTOM. 5 = COMPETING
  STREAM_URL: "https://www.youtube.com/watch?v=F-wbcMyeq4A" # set stream url activity, support youtube, twitch only
  BOT_STATUS: "idle" # online, idle, dnd, invisible
  CUSTOM_STATUS: "MADE BY TRAGIC" # set custom status if type is 4

  IMGURL_GUILDADD: "https://cdn.is-a.fun/bot/mewwme/thankyou.png"
  IMGURL_MENUHELP: "https://cdn.is-a.fun/bot/mewwme/help.png"
  IMGURL_COMMANDMENU: "https://cdn.is-a.fun/mewwme/mewwme.gif"
  REQUEST_IMAGE: "https://cdn.is-a.fun/bot/mewwme/req.png"
  IMGURL_MENTION: "https://cdn.is-a.fun/bot/mewwme/help.png"

  # button link
  DEVELOPER_NAME: "L RMN"
  DEVELOPER_URL: "https://is-a.fun"
  DONATE_URL: "https://www.patreon.com/mewwme"
  SERVER_SUPPORT: "https://discord.gg/mewwme"
  VOTE_URL: "https://top.gg/bot/928711702596423740"
  INVITE_URL: "https://discord.com/api/oauth2/authorize?client_id=928711702596423740&permissions=551940385840&response_type=code&redirect_uri=https%3A%2F%2Fdiscord.gg%2Fmewwme&scope=guilds.join+bot+applications.commands"

lavalink:
  SEARCH_ENGINE: "youtube_music" # default ( youtube, youtube_music, soundcloud )
    # Your spotify id and secret, you can get it from here: https://developer.spotify.com/
    # If you don't have or don't want, you can disable it
  SPOTIFY:
    enable: true
    id: fdf0e2d1da9e40169b5918f73addae04
    secret: db0fa34ff766490e87e9996c0ae844e0

  DEFAULT: ["yoasobi", "one oke rock", "blackpink"]

  NP_REALTIME: false #beta (Enable this if you want to use realtime duation in nowplaying command)

  LEAVE_TIMEOUT: 300000 # The number of leave time you want

  # You can add more lavalink server!
  NODES:
    [
      # node region Asia/Jakarta
      {
        url: "34.142.204.199:2333",
        name: "mewwme",
        auth: "madebytragic",
        secure: false,
      },
    ]
  SHOUKAKU_OPTIONS:
    {
      moveOnDisconnect: true,
      resumable: true,
      resumableTimeout: 600,
      reconnectTries: "Infinity",
      restTimeout: 3000,
    }


features:
    # Note: If you enter an invalid driver, bot will use json driver as default
    # Config depend on driver, you can see sample config at src/database/driver
    # mongodb, mysql, json, postgres
  DATABASE:
    driver: "json" # mongodb, mysql, json, postgres
    config: { path: "./mewwme.database.json" }

  MESSAGE_CONTENT:
    enable: true
    commands:
      enable: true
      prefix: ">" # The prefix you want

  AUTOFIX_LAVALINK: # Fix the lavalink server when the current is down
    enable: true
    reconnectTries: 1
    restTimeout: 3000

  WEB_SERVER:
    enable: true # Must enable this before using ws
    PORT: 3026
    websocket:
      enable: true
      host: "0.0.0.0" # Default is 0.0.0.0
      secret: "-19023454588-MEWWME" # You must add your secret key to use ws. A secret key is anything you want
      auth: true
      trusted: ["http://localhost:3026"]

  # Your id or friend id (disable global command)
  DEV_ID: []

# Emoji config for discord message content in select menu
# https://discord.gg/mewwme join the discord server if you want to use existing emoji
Emoji:
  E_HOME: "<:home:1193100237133336670>"
  E_ADMIN: "<:admin:1193100129020944454>"
  E_DEV: "<:devme:1203372399135957012>"
  E_SETTING: "<:setting:1193100341261119598>"
  E_FILTER: "<:switch:1196007160279203841>"
  E_PLAYLIST: "<:playlist:1193105976694407208>"
  E_UTILS: "<:utils:1203371744900153436>"
  E_ALLCMD: "<:meall:1193100157928099931>"
  E_MUSIC: "<:disc:1196006944746524764>"
  E_INFO: "<:info:1193100286881964104>"
  E_LOADING: "<a:loading:1169254882193186847>"

ServerSupport:
# set channel support for bot event
  UPDATE_CHANNEL_ID: "1198207171075252305"
  SUGGESTION_CHANNEL_ID: "1198207171075252305"
  BUG_REPORT_CHANNEL_ID: "1198207171075252305"
# set webhook url settings for bot guild add/guild remove logs
  BOTLOGS_JOINLEFT: "https://canary.discord.com/api/webhooks/1205083115551330354/s0LkE9opL0K7pHsKn4v63qdZ9aKUdpLxWdRP9UvN4TKhpLAuHjDlNQMf5fHZIm_lD1jv"
# set webhook url settings for redeem logs
  REDEEM_LOGS: "https://canary.discord.com/api/webhooks/1205083115551330354/s0LkE9opL0K7pHsKn4v63qdZ9aKUdpLxWdRP9UvN4TKhpLAuHjDlNQMf5fHZIm_lD1jv"

